Fix code generation issue for python
jaegertracing/jaeger-idl pull request #67
Opened 2020-12-11 10:03 UTC by lonewolf3739

Signed-off-by: Srikanth Chekuri <srikanth.chekuri92@gmail.com>

## Which problem is this PR solving?
Fixes https://github.com/jaegertracing/docker-protobuf/issues/24

## Short description of the changes
**proto-gen-python** can not be used because `google/api/annotations.proto`, `gogoproto/gogo.proto` and `protoc-gen-swagger/options/annotations.proto` are not created but required to use the `model` or `collector` generated files.

Update the Makefile to `generate google/api/annotations.proto`, `gogoproto/gogo.proto` and `protoc-gen-swagger/options/annotations.proto`

2020-12-11 10:23 UTC, Falco20019 commented
I would suggest merging `PROTOC_CS_INTERNAL` and `PROTOC_PY_INTERNAL` into `PROTOC_INTERNAL` Since they are called with the same file list. Just add the `python_out` right after the `csharp_out`.

2020-12-11 10:25 UTC, Falco20019 requested changes

2020-12-11 10:26 UTC, Falco20019 commented
Just a small suggestion avoid cluttering the file since the goal and file list is the same for CS and PY.

2020-12-11 10:28 UTC, lonewolf3739 commented on Makefile
> +	$(PROTOC_PY_INTERNAL) \
Yeah, makes sense. I will change it.

2020-12-11 10:29 UTC, Falco20019 commented on Makefile
> +	$(PROTOC_PY_INTERNAL) \
Or put it before to keep the order similar to `PROTOC_WITHOUT_GRPC`

2020-12-11 10:32 UTC, Falco20019 commented
You might also want to add a „Fixes https://github.com/jaegertracing/jaeger-client-csharp/issues/197“ to the initial post 👍

2020-12-11 14:28 UTC, lonewolf3739 commented on Makefile
>  		--csharp_out=internal_access,base_namespace:${PROTO_GEN_CSHARP_DIR}
Updated. I wish it gave error when I ran `make proto` but it ran silently without any error.

2020-12-11 14:31 UTC, Falco20019 approved these changes
LGTM. If travis goes green, I‘m fine with merging

2020-12-11 14:33 UTC, Falco20019 commented
@yurishkuro I have no write permission, so my review is not worth too much. But looks promising from my side. So if it runs for you, feel free to also give it a look and approve.

2020-12-11 17:13 UTC, yurishkuro commented
1. since Travis-CI decided to deny us any credits, we need to add GH Action for this repo (as we already did in many others) to see that the CI build is succeeding
2. it is not clear to me how this is actually fixing the linked issues. The Makefile in this repo is merely a sanity check that `protoc` can run successfully. Are we saying that this Makefile is how we want people to generate stubs? If so, we should make it explicit in the README.
3. But even with (2), we're not actually testing the generated stubs, otherwise we would've discovered this issue with Python. So ideally we'd have some basic test programs for each language that try to import the stubs and do a roundtrip encode-decode (does not need to be a part of this PR).

2020-12-11 18:15 UTC, Falco20019 commented
I think only the library maintainer would need to do this in most cases. End users usually can just use however the library maintainer for the language decided to package those generated files. Due to the dependency on those five protos, there is no easy way to generate the necessary code other than using this Makefile or by doing the same stuff that the docker does with the wrapper (downloading everything and so on) and then doing the steps in this Makefile.

It might be hard to do the roundtrips only by the generated files. We would still need some bootstrapped per language and maybe some tests like with xdock. But since this is mostly necessary for a small group like 1-2 persons per language, I‘m not sure if it‘s worth the effort.

2020-12-11 18:32 UTC, lonewolf3739 commented
> Due to the dependency on those five protos, there is no easy way to generate the necessary code other than using this Makefile

Yes, it wasn't clear how to get around with `gogo.proto`, `.../annotations.proto` etc.. I think this will become problem for other language clients as well. As of now C# is the only client that supports sending via gRPC and as I am trying with python I came across this problem. As suggested by @yurishkuro maybe we should recommend generating stubs with `make`?

2020-12-12 00:19 UTC, yurishkuro approved these changes

2020-12-12 00:20 UTC, merged